/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppearanceRouteImport } from './routes/appearance'
import { Route as ChgstrippedRouteImport } from './routes/chgstripped'
import { Route as NewReleaseRouteImport } from './routes/new-release'
import { Route as PressRouteImport } from './routes/press'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as XoxoImDoneAfterHoursRouteImport } from './routes/xoxo-im-done-after-hours'
import { Route as YckmnRouteImport } from './routes/yckmn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppearanceRoute = AppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const ChgstrippedRoute = ChgstrippedRouteImport.update({
  id: '/chgstripped',
  path: '/chgstripped',
  getParentRoute: () => rootRouteImport,
} as any)
const NewReleaseRoute = NewReleaseRouteImport.update({
  id: '/new-release',
  path: '/new-release',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const XoxoImDoneAfterHoursRoute = XoxoImDoneAfterHoursRouteImport.update({
  id: '/xoxo-im-done-after-hours',
  path: '/xoxo-im-done-after-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const YckmnRoute = YckmnRouteImport.update({
  id: '/yckmn',
  path: '/yckmn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appearance': typeof AppearanceRoute
  '/chgstripped': typeof ChgstrippedRoute
  '/new-release': typeof NewReleaseRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/xoxo-im-done-after-hours': typeof XoxoImDoneAfterHoursRoute
  '/yckmn': typeof YckmnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appearance': typeof AppearanceRoute
  '/chgstripped': typeof ChgstrippedRoute
  '/new-release': typeof NewReleaseRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/xoxo-im-done-after-hours': typeof XoxoImDoneAfterHoursRoute
  '/yckmn': typeof YckmnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appearance': typeof AppearanceRoute
  '/chgstripped': typeof ChgstrippedRoute
  '/new-release': typeof NewReleaseRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/xoxo-im-done-after-hours': typeof XoxoImDoneAfterHoursRoute
  '/yckmn': typeof YckmnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appearance'
    | '/chgstripped'
    | '/new-release'
    | '/press'
    | '/privacy'
    | '/store'
    | '/terms'
    | '/xoxo-im-done-after-hours'
    | '/yckmn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appearance'
    | '/chgstripped'
    | '/new-release'
    | '/press'
    | '/privacy'
    | '/store'
    | '/terms'
    | '/xoxo-im-done-after-hours'
    | '/yckmn'
  id:
    | '__root__'
    | '/'
    | '/appearance'
    | '/chgstripped'
    | '/new-release'
    | '/press'
    | '/privacy'
    | '/store'
    | '/terms'
    | '/xoxo-im-done-after-hours'
    | '/yckmn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppearanceRoute: typeof AppearanceRoute
  ChgstrippedRoute: typeof ChgstrippedRoute
  NewReleaseRoute: typeof NewReleaseRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  StoreRoute: typeof StoreRoute
  TermsRoute: typeof TermsRoute
  XoxoImDoneAfterHoursRoute: typeof XoxoImDoneAfterHoursRoute
  YckmnRoute: typeof YckmnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appearance': {
      id: '/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chgstripped': {
      id: '/chgstripped'
      path: '/chgstripped'
      fullPath: '/chgstripped'
      preLoaderRoute: typeof ChgstrippedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-release': {
      id: '/new-release'
      path: '/new-release'
      fullPath: '/new-release'
      preLoaderRoute: typeof NewReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xoxo-im-done-after-hours': {
      id: '/xoxo-im-done-after-hours'
      path: '/xoxo-im-done-after-hours'
      fullPath: '/xoxo-im-done-after-hours'
      preLoaderRoute: typeof XoxoImDoneAfterHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yckmn': {
      id: '/yckmn'
      path: '/yckmn'
      fullPath: '/yckmn'
      preLoaderRoute: typeof YckmnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppearanceRoute: AppearanceRoute,
  ChgstrippedRoute: ChgstrippedRoute,
  NewReleaseRoute: NewReleaseRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  StoreRoute: StoreRoute,
  TermsRoute: TermsRoute,
  XoxoImDoneAfterHoursRoute: XoxoImDoneAfterHoursRoute,
  YckmnRoute: YckmnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
